/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RequestAuditRouteImport } from './routes/request-audit'
import { Route as ProjectEstimatorRouteImport } from './routes/project-estimator'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersApplyRouteImport } from './routes/careers-apply'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDevelopmentRouteImport } from './routes/services/web-development'
import { Route as ServicesNetworkRouteImport } from './routes/services/network'
import { Route as ServicesMobileRouteImport } from './routes/services/mobile'
import { Route as ServicesMarketingRouteImport } from './routes/services/marketing'
import { Route as ServicesManagedItRouteImport } from './routes/services/managed-it'
import { Route as ServicesItStaffingRouteImport } from './routes/services/it-staffing'
import { Route as ServicesErpRouteImport } from './routes/services/erp'
import { Route as ServicesCyberSecurityRouteImport } from './routes/services/cyber-security'
import { Route as ServicesCustomSoftwareRouteImport } from './routes/services/custom-software'
import { Route as ServicesConsultingRouteImport } from './routes/services/consulting'
import { Route as ServicesCloudRouteImport } from './routes/services/cloud'
import { Route as ServicesBlockchainRouteImport } from './routes/services/blockchain'
import { Route as ResourcesZeroTrustArchitectureRouteImport } from './routes/resources/zero-trust-architecture'
import { Route as ResourcesWhatIsVcioRouteImport } from './routes/resources/what-is-vcio'
import { Route as ResourcesSocExplainedRouteImport } from './routes/resources/soc-explained'
import { Route as ResourcesRansomwareRecoveryRouteImport } from './routes/resources/ransomware-recovery'
import { Route as ResourcesPenetrationTestingExplainedRouteImport } from './routes/resources/penetration-testing-explained'
import { Route as ResourcesItStaffingVsInHouseRouteImport } from './routes/resources/it-staffing-vs-in-house'
import { Route as ResourcesIso27001ChecklistRouteImport } from './routes/resources/iso-27001-checklist'
import { Route as ResourcesInHouseItVsManagedServicesRouteImport } from './routes/resources/in-house-it-vs-managed-services'
import { Route as ResourcesGlossaryRouteImport } from './routes/resources/glossary'
import { Route as ResourcesGenerativeAiEnterpriseRouteImport } from './routes/resources/generative-ai-enterprise'
import { Route as ResourcesErpVsSapRouteImport } from './routes/resources/erp-vs-sap'
import { Route as ResourcesCyberEssentialsGuideRouteImport } from './routes/resources/cyber-essentials-guide'
import { Route as ResourcesCloudMigrationCostGuideRouteImport } from './routes/resources/cloud-migration-cost-guide'
import { Route as ResourcesBlockchainSupplyChainRouteImport } from './routes/resources/blockchain-supply-chain'
import { Route as ResourcesBcdrGuideRouteImport } from './routes/resources/bcdr-guide'
import { Route as ResourcesAiAgentsEnterpriseGuideRouteImport } from './routes/resources/ai-agents-enterprise-guide'
import { Route as IndustriesManufacturingRouteImport } from './routes/industries/manufacturing'
import { Route as IndustriesHealthcareRouteImport } from './routes/industries/healthcare'
import { Route as IndustriesFintechRouteImport } from './routes/industries/fintech'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAuditRoute = RequestAuditRouteImport.update({
  id: '/request-audit',
  path: '/request-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectEstimatorRoute = ProjectEstimatorRouteImport.update({
  id: '/project-estimator',
  path: '/project-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersApplyRoute = CareersApplyRouteImport.update({
  id: '/careers-apply',
  path: '/careers-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDevelopmentRoute = ServicesWebDevelopmentRouteImport.update({
  id: '/services/web-development',
  path: '/services/web-development',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesNetworkRoute = ServicesNetworkRouteImport.update({
  id: '/services/network',
  path: '/services/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMobileRoute = ServicesMobileRouteImport.update({
  id: '/services/mobile',
  path: '/services/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMarketingRoute = ServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesManagedItRoute = ServicesManagedItRouteImport.update({
  id: '/services/managed-it',
  path: '/services/managed-it',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesItStaffingRoute = ServicesItStaffingRouteImport.update({
  id: '/services/it-staffing',
  path: '/services/it-staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesErpRoute = ServicesErpRouteImport.update({
  id: '/services/erp',
  path: '/services/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCyberSecurityRoute = ServicesCyberSecurityRouteImport.update({
  id: '/services/cyber-security',
  path: '/services/cyber-security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCustomSoftwareRoute = ServicesCustomSoftwareRouteImport.update({
  id: '/services/custom-software',
  path: '/services/custom-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultingRoute = ServicesConsultingRouteImport.update({
  id: '/services/consulting',
  path: '/services/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudRoute = ServicesCloudRouteImport.update({
  id: '/services/cloud',
  path: '/services/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBlockchainRoute = ServicesBlockchainRouteImport.update({
  id: '/services/blockchain',
  path: '/services/blockchain',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesZeroTrustArchitectureRoute =
  ResourcesZeroTrustArchitectureRouteImport.update({
    id: '/resources/zero-trust-architecture',
    path: '/resources/zero-trust-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesWhatIsVcioRoute = ResourcesWhatIsVcioRouteImport.update({
  id: '/resources/what-is-vcio',
  path: '/resources/what-is-vcio',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSocExplainedRoute = ResourcesSocExplainedRouteImport.update({
  id: '/resources/soc-explained',
  path: '/resources/soc-explained',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRansomwareRecoveryRoute =
  ResourcesRansomwareRecoveryRouteImport.update({
    id: '/resources/ransomware-recovery',
    path: '/resources/ransomware-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesPenetrationTestingExplainedRoute =
  ResourcesPenetrationTestingExplainedRouteImport.update({
    id: '/resources/penetration-testing-explained',
    path: '/resources/penetration-testing-explained',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesItStaffingVsInHouseRoute =
  ResourcesItStaffingVsInHouseRouteImport.update({
    id: '/resources/it-staffing-vs-in-house',
    path: '/resources/it-staffing-vs-in-house',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesIso27001ChecklistRoute =
  ResourcesIso27001ChecklistRouteImport.update({
    id: '/resources/iso-27001-checklist',
    path: '/resources/iso-27001-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesInHouseItVsManagedServicesRoute =
  ResourcesInHouseItVsManagedServicesRouteImport.update({
    id: '/resources/in-house-it-vs-managed-services',
    path: '/resources/in-house-it-vs-managed-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesGlossaryRoute = ResourcesGlossaryRouteImport.update({
  id: '/resources/glossary',
  path: '/resources/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesGenerativeAiEnterpriseRoute =
  ResourcesGenerativeAiEnterpriseRouteImport.update({
    id: '/resources/generative-ai-enterprise',
    path: '/resources/generative-ai-enterprise',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesErpVsSapRoute = ResourcesErpVsSapRouteImport.update({
  id: '/resources/erp-vs-sap',
  path: '/resources/erp-vs-sap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCyberEssentialsGuideRoute =
  ResourcesCyberEssentialsGuideRouteImport.update({
    id: '/resources/cyber-essentials-guide',
    path: '/resources/cyber-essentials-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesCloudMigrationCostGuideRoute =
  ResourcesCloudMigrationCostGuideRouteImport.update({
    id: '/resources/cloud-migration-cost-guide',
    path: '/resources/cloud-migration-cost-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesBlockchainSupplyChainRoute =
  ResourcesBlockchainSupplyChainRouteImport.update({
    id: '/resources/blockchain-supply-chain',
    path: '/resources/blockchain-supply-chain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesBcdrGuideRoute = ResourcesBcdrGuideRouteImport.update({
  id: '/resources/bcdr-guide',
  path: '/resources/bcdr-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAiAgentsEnterpriseGuideRoute =
  ResourcesAiAgentsEnterpriseGuideRouteImport.update({
    id: '/resources/ai-agents-enterprise-guide',
    path: '/resources/ai-agents-enterprise-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesManufacturingRoute = IndustriesManufacturingRouteImport.update({
  id: '/industries/manufacturing',
  path: '/industries/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesHealthcareRoute = IndustriesHealthcareRouteImport.update({
  id: '/industries/healthcare',
  path: '/industries/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFintechRoute = IndustriesFintechRouteImport.update({
  id: '/industries/fintech',
  path: '/industries/fintech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/careers-apply': typeof CareersApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/request-audit': typeof RequestAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/industries/fintech': typeof IndustriesFintechRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/resources/ai-agents-enterprise-guide': typeof ResourcesAiAgentsEnterpriseGuideRoute
  '/resources/bcdr-guide': typeof ResourcesBcdrGuideRoute
  '/resources/blockchain-supply-chain': typeof ResourcesBlockchainSupplyChainRoute
  '/resources/cloud-migration-cost-guide': typeof ResourcesCloudMigrationCostGuideRoute
  '/resources/cyber-essentials-guide': typeof ResourcesCyberEssentialsGuideRoute
  '/resources/erp-vs-sap': typeof ResourcesErpVsSapRoute
  '/resources/generative-ai-enterprise': typeof ResourcesGenerativeAiEnterpriseRoute
  '/resources/glossary': typeof ResourcesGlossaryRoute
  '/resources/in-house-it-vs-managed-services': typeof ResourcesInHouseItVsManagedServicesRoute
  '/resources/iso-27001-checklist': typeof ResourcesIso27001ChecklistRoute
  '/resources/it-staffing-vs-in-house': typeof ResourcesItStaffingVsInHouseRoute
  '/resources/penetration-testing-explained': typeof ResourcesPenetrationTestingExplainedRoute
  '/resources/ransomware-recovery': typeof ResourcesRansomwareRecoveryRoute
  '/resources/soc-explained': typeof ResourcesSocExplainedRoute
  '/resources/what-is-vcio': typeof ResourcesWhatIsVcioRoute
  '/resources/zero-trust-architecture': typeof ResourcesZeroTrustArchitectureRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/managed-it': typeof ServicesManagedItRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/network': typeof ServicesNetworkRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/careers-apply': typeof CareersApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/request-audit': typeof RequestAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/industries/fintech': typeof IndustriesFintechRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/resources/ai-agents-enterprise-guide': typeof ResourcesAiAgentsEnterpriseGuideRoute
  '/resources/bcdr-guide': typeof ResourcesBcdrGuideRoute
  '/resources/blockchain-supply-chain': typeof ResourcesBlockchainSupplyChainRoute
  '/resources/cloud-migration-cost-guide': typeof ResourcesCloudMigrationCostGuideRoute
  '/resources/cyber-essentials-guide': typeof ResourcesCyberEssentialsGuideRoute
  '/resources/erp-vs-sap': typeof ResourcesErpVsSapRoute
  '/resources/generative-ai-enterprise': typeof ResourcesGenerativeAiEnterpriseRoute
  '/resources/glossary': typeof ResourcesGlossaryRoute
  '/resources/in-house-it-vs-managed-services': typeof ResourcesInHouseItVsManagedServicesRoute
  '/resources/iso-27001-checklist': typeof ResourcesIso27001ChecklistRoute
  '/resources/it-staffing-vs-in-house': typeof ResourcesItStaffingVsInHouseRoute
  '/resources/penetration-testing-explained': typeof ResourcesPenetrationTestingExplainedRoute
  '/resources/ransomware-recovery': typeof ResourcesRansomwareRecoveryRoute
  '/resources/soc-explained': typeof ResourcesSocExplainedRoute
  '/resources/what-is-vcio': typeof ResourcesWhatIsVcioRoute
  '/resources/zero-trust-architecture': typeof ResourcesZeroTrustArchitectureRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/managed-it': typeof ServicesManagedItRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/network': typeof ServicesNetworkRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/capabilities': typeof CapabilitiesRoute
  '/careers': typeof CareersRoute
  '/careers-apply': typeof CareersApplyRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/insights': typeof InsightsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/request-audit': typeof RequestAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/industries/fintech': typeof IndustriesFintechRoute
  '/industries/healthcare': typeof IndustriesHealthcareRoute
  '/industries/manufacturing': typeof IndustriesManufacturingRoute
  '/resources/ai-agents-enterprise-guide': typeof ResourcesAiAgentsEnterpriseGuideRoute
  '/resources/bcdr-guide': typeof ResourcesBcdrGuideRoute
  '/resources/blockchain-supply-chain': typeof ResourcesBlockchainSupplyChainRoute
  '/resources/cloud-migration-cost-guide': typeof ResourcesCloudMigrationCostGuideRoute
  '/resources/cyber-essentials-guide': typeof ResourcesCyberEssentialsGuideRoute
  '/resources/erp-vs-sap': typeof ResourcesErpVsSapRoute
  '/resources/generative-ai-enterprise': typeof ResourcesGenerativeAiEnterpriseRoute
  '/resources/glossary': typeof ResourcesGlossaryRoute
  '/resources/in-house-it-vs-managed-services': typeof ResourcesInHouseItVsManagedServicesRoute
  '/resources/iso-27001-checklist': typeof ResourcesIso27001ChecklistRoute
  '/resources/it-staffing-vs-in-house': typeof ResourcesItStaffingVsInHouseRoute
  '/resources/penetration-testing-explained': typeof ResourcesPenetrationTestingExplainedRoute
  '/resources/ransomware-recovery': typeof ResourcesRansomwareRecoveryRoute
  '/resources/soc-explained': typeof ResourcesSocExplainedRoute
  '/resources/what-is-vcio': typeof ResourcesWhatIsVcioRoute
  '/resources/zero-trust-architecture': typeof ResourcesZeroTrustArchitectureRoute
  '/services/blockchain': typeof ServicesBlockchainRoute
  '/services/cloud': typeof ServicesCloudRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/custom-software': typeof ServicesCustomSoftwareRoute
  '/services/cyber-security': typeof ServicesCyberSecurityRoute
  '/services/erp': typeof ServicesErpRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/managed-it': typeof ServicesManagedItRoute
  '/services/marketing': typeof ServicesMarketingRoute
  '/services/mobile': typeof ServicesMobileRoute
  '/services/network': typeof ServicesNetworkRoute
  '/services/web-development': typeof ServicesWebDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/capabilities'
    | '/careers'
    | '/careers-apply'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/products'
    | '/project-estimator'
    | '/request-audit'
    | '/sitemap.xml'
    | '/team'
    | '/technology'
    | '/terms'
    | '/industries/fintech'
    | '/industries/healthcare'
    | '/industries/manufacturing'
    | '/resources/ai-agents-enterprise-guide'
    | '/resources/bcdr-guide'
    | '/resources/blockchain-supply-chain'
    | '/resources/cloud-migration-cost-guide'
    | '/resources/cyber-essentials-guide'
    | '/resources/erp-vs-sap'
    | '/resources/generative-ai-enterprise'
    | '/resources/glossary'
    | '/resources/in-house-it-vs-managed-services'
    | '/resources/iso-27001-checklist'
    | '/resources/it-staffing-vs-in-house'
    | '/resources/penetration-testing-explained'
    | '/resources/ransomware-recovery'
    | '/resources/soc-explained'
    | '/resources/what-is-vcio'
    | '/resources/zero-trust-architecture'
    | '/services/blockchain'
    | '/services/cloud'
    | '/services/consulting'
    | '/services/custom-software'
    | '/services/cyber-security'
    | '/services/erp'
    | '/services/it-staffing'
    | '/services/managed-it'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/network'
    | '/services/web-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/capabilities'
    | '/careers'
    | '/careers-apply'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/products'
    | '/project-estimator'
    | '/request-audit'
    | '/sitemap.xml'
    | '/team'
    | '/technology'
    | '/terms'
    | '/industries/fintech'
    | '/industries/healthcare'
    | '/industries/manufacturing'
    | '/resources/ai-agents-enterprise-guide'
    | '/resources/bcdr-guide'
    | '/resources/blockchain-supply-chain'
    | '/resources/cloud-migration-cost-guide'
    | '/resources/cyber-essentials-guide'
    | '/resources/erp-vs-sap'
    | '/resources/generative-ai-enterprise'
    | '/resources/glossary'
    | '/resources/in-house-it-vs-managed-services'
    | '/resources/iso-27001-checklist'
    | '/resources/it-staffing-vs-in-house'
    | '/resources/penetration-testing-explained'
    | '/resources/ransomware-recovery'
    | '/resources/soc-explained'
    | '/resources/what-is-vcio'
    | '/resources/zero-trust-architecture'
    | '/services/blockchain'
    | '/services/cloud'
    | '/services/consulting'
    | '/services/custom-software'
    | '/services/cyber-security'
    | '/services/erp'
    | '/services/it-staffing'
    | '/services/managed-it'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/network'
    | '/services/web-development'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/capabilities'
    | '/careers'
    | '/careers-apply'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/insights'
    | '/marketing'
    | '/pricing'
    | '/privacy-policy'
    | '/process'
    | '/products'
    | '/project-estimator'
    | '/request-audit'
    | '/sitemap.xml'
    | '/team'
    | '/technology'
    | '/terms'
    | '/industries/fintech'
    | '/industries/healthcare'
    | '/industries/manufacturing'
    | '/resources/ai-agents-enterprise-guide'
    | '/resources/bcdr-guide'
    | '/resources/blockchain-supply-chain'
    | '/resources/cloud-migration-cost-guide'
    | '/resources/cyber-essentials-guide'
    | '/resources/erp-vs-sap'
    | '/resources/generative-ai-enterprise'
    | '/resources/glossary'
    | '/resources/in-house-it-vs-managed-services'
    | '/resources/iso-27001-checklist'
    | '/resources/it-staffing-vs-in-house'
    | '/resources/penetration-testing-explained'
    | '/resources/ransomware-recovery'
    | '/resources/soc-explained'
    | '/resources/what-is-vcio'
    | '/resources/zero-trust-architecture'
    | '/services/blockchain'
    | '/services/cloud'
    | '/services/consulting'
    | '/services/custom-software'
    | '/services/cyber-security'
    | '/services/erp'
    | '/services/it-staffing'
    | '/services/managed-it'
    | '/services/marketing'
    | '/services/mobile'
    | '/services/network'
    | '/services/web-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  CareersRoute: typeof CareersRoute
  CareersApplyRoute: typeof CareersApplyRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  InsightsRoute: typeof InsightsRoute
  MarketingRoute: typeof MarketingRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProcessRoute: typeof ProcessRoute
  ProductsRoute: typeof ProductsRoute
  ProjectEstimatorRoute: typeof ProjectEstimatorRoute
  RequestAuditRoute: typeof RequestAuditRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  IndustriesFintechRoute: typeof IndustriesFintechRoute
  IndustriesHealthcareRoute: typeof IndustriesHealthcareRoute
  IndustriesManufacturingRoute: typeof IndustriesManufacturingRoute
  ResourcesAiAgentsEnterpriseGuideRoute: typeof ResourcesAiAgentsEnterpriseGuideRoute
  ResourcesBcdrGuideRoute: typeof ResourcesBcdrGuideRoute
  ResourcesBlockchainSupplyChainRoute: typeof ResourcesBlockchainSupplyChainRoute
  ResourcesCloudMigrationCostGuideRoute: typeof ResourcesCloudMigrationCostGuideRoute
  ResourcesCyberEssentialsGuideRoute: typeof ResourcesCyberEssentialsGuideRoute
  ResourcesErpVsSapRoute: typeof ResourcesErpVsSapRoute
  ResourcesGenerativeAiEnterpriseRoute: typeof ResourcesGenerativeAiEnterpriseRoute
  ResourcesGlossaryRoute: typeof ResourcesGlossaryRoute
  ResourcesInHouseItVsManagedServicesRoute: typeof ResourcesInHouseItVsManagedServicesRoute
  ResourcesIso27001ChecklistRoute: typeof ResourcesIso27001ChecklistRoute
  ResourcesItStaffingVsInHouseRoute: typeof ResourcesItStaffingVsInHouseRoute
  ResourcesPenetrationTestingExplainedRoute: typeof ResourcesPenetrationTestingExplainedRoute
  ResourcesRansomwareRecoveryRoute: typeof ResourcesRansomwareRecoveryRoute
  ResourcesSocExplainedRoute: typeof ResourcesSocExplainedRoute
  ResourcesWhatIsVcioRoute: typeof ResourcesWhatIsVcioRoute
  ResourcesZeroTrustArchitectureRoute: typeof ResourcesZeroTrustArchitectureRoute
  ServicesBlockchainRoute: typeof ServicesBlockchainRoute
  ServicesCloudRoute: typeof ServicesCloudRoute
  ServicesConsultingRoute: typeof ServicesConsultingRoute
  ServicesCustomSoftwareRoute: typeof ServicesCustomSoftwareRoute
  ServicesCyberSecurityRoute: typeof ServicesCyberSecurityRoute
  ServicesErpRoute: typeof ServicesErpRoute
  ServicesItStaffingRoute: typeof ServicesItStaffingRoute
  ServicesManagedItRoute: typeof ServicesManagedItRoute
  ServicesMarketingRoute: typeof ServicesMarketingRoute
  ServicesMobileRoute: typeof ServicesMobileRoute
  ServicesNetworkRoute: typeof ServicesNetworkRoute
  ServicesWebDevelopmentRoute: typeof ServicesWebDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-audit': {
      id: '/request-audit'
      path: '/request-audit'
      fullPath: '/request-audit'
      preLoaderRoute: typeof RequestAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-estimator': {
      id: '/project-estimator'
      path: '/project-estimator'
      fullPath: '/project-estimator'
      preLoaderRoute: typeof ProjectEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers-apply': {
      id: '/careers-apply'
      path: '/careers-apply'
      fullPath: '/careers-apply'
      preLoaderRoute: typeof CareersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-development': {
      id: '/services/web-development'
      path: '/services/web-development'
      fullPath: '/services/web-development'
      preLoaderRoute: typeof ServicesWebDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/network': {
      id: '/services/network'
      path: '/services/network'
      fullPath: '/services/network'
      preLoaderRoute: typeof ServicesNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mobile': {
      id: '/services/mobile'
      path: '/services/mobile'
      fullPath: '/services/mobile'
      preLoaderRoute: typeof ServicesMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/marketing': {
      id: '/services/marketing'
      path: '/services/marketing'
      fullPath: '/services/marketing'
      preLoaderRoute: typeof ServicesMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/managed-it': {
      id: '/services/managed-it'
      path: '/services/managed-it'
      fullPath: '/services/managed-it'
      preLoaderRoute: typeof ServicesManagedItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/it-staffing': {
      id: '/services/it-staffing'
      path: '/services/it-staffing'
      fullPath: '/services/it-staffing'
      preLoaderRoute: typeof ServicesItStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/erp': {
      id: '/services/erp'
      path: '/services/erp'
      fullPath: '/services/erp'
      preLoaderRoute: typeof ServicesErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cyber-security': {
      id: '/services/cyber-security'
      path: '/services/cyber-security'
      fullPath: '/services/cyber-security'
      preLoaderRoute: typeof ServicesCyberSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-software': {
      id: '/services/custom-software'
      path: '/services/custom-software'
      fullPath: '/services/custom-software'
      preLoaderRoute: typeof ServicesCustomSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consulting': {
      id: '/services/consulting'
      path: '/services/consulting'
      fullPath: '/services/consulting'
      preLoaderRoute: typeof ServicesConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud': {
      id: '/services/cloud'
      path: '/services/cloud'
      fullPath: '/services/cloud'
      preLoaderRoute: typeof ServicesCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/blockchain': {
      id: '/services/blockchain'
      path: '/services/blockchain'
      fullPath: '/services/blockchain'
      preLoaderRoute: typeof ServicesBlockchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/zero-trust-architecture': {
      id: '/resources/zero-trust-architecture'
      path: '/resources/zero-trust-architecture'
      fullPath: '/resources/zero-trust-architecture'
      preLoaderRoute: typeof ResourcesZeroTrustArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/what-is-vcio': {
      id: '/resources/what-is-vcio'
      path: '/resources/what-is-vcio'
      fullPath: '/resources/what-is-vcio'
      preLoaderRoute: typeof ResourcesWhatIsVcioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/soc-explained': {
      id: '/resources/soc-explained'
      path: '/resources/soc-explained'
      fullPath: '/resources/soc-explained'
      preLoaderRoute: typeof ResourcesSocExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/ransomware-recovery': {
      id: '/resources/ransomware-recovery'
      path: '/resources/ransomware-recovery'
      fullPath: '/resources/ransomware-recovery'
      preLoaderRoute: typeof ResourcesRansomwareRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/penetration-testing-explained': {
      id: '/resources/penetration-testing-explained'
      path: '/resources/penetration-testing-explained'
      fullPath: '/resources/penetration-testing-explained'
      preLoaderRoute: typeof ResourcesPenetrationTestingExplainedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/it-staffing-vs-in-house': {
      id: '/resources/it-staffing-vs-in-house'
      path: '/resources/it-staffing-vs-in-house'
      fullPath: '/resources/it-staffing-vs-in-house'
      preLoaderRoute: typeof ResourcesItStaffingVsInHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/iso-27001-checklist': {
      id: '/resources/iso-27001-checklist'
      path: '/resources/iso-27001-checklist'
      fullPath: '/resources/iso-27001-checklist'
      preLoaderRoute: typeof ResourcesIso27001ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/in-house-it-vs-managed-services': {
      id: '/resources/in-house-it-vs-managed-services'
      path: '/resources/in-house-it-vs-managed-services'
      fullPath: '/resources/in-house-it-vs-managed-services'
      preLoaderRoute: typeof ResourcesInHouseItVsManagedServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/glossary': {
      id: '/resources/glossary'
      path: '/resources/glossary'
      fullPath: '/resources/glossary'
      preLoaderRoute: typeof ResourcesGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/generative-ai-enterprise': {
      id: '/resources/generative-ai-enterprise'
      path: '/resources/generative-ai-enterprise'
      fullPath: '/resources/generative-ai-enterprise'
      preLoaderRoute: typeof ResourcesGenerativeAiEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/erp-vs-sap': {
      id: '/resources/erp-vs-sap'
      path: '/resources/erp-vs-sap'
      fullPath: '/resources/erp-vs-sap'
      preLoaderRoute: typeof ResourcesErpVsSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/cyber-essentials-guide': {
      id: '/resources/cyber-essentials-guide'
      path: '/resources/cyber-essentials-guide'
      fullPath: '/resources/cyber-essentials-guide'
      preLoaderRoute: typeof ResourcesCyberEssentialsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/cloud-migration-cost-guide': {
      id: '/resources/cloud-migration-cost-guide'
      path: '/resources/cloud-migration-cost-guide'
      fullPath: '/resources/cloud-migration-cost-guide'
      preLoaderRoute: typeof ResourcesCloudMigrationCostGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blockchain-supply-chain': {
      id: '/resources/blockchain-supply-chain'
      path: '/resources/blockchain-supply-chain'
      fullPath: '/resources/blockchain-supply-chain'
      preLoaderRoute: typeof ResourcesBlockchainSupplyChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/bcdr-guide': {
      id: '/resources/bcdr-guide'
      path: '/resources/bcdr-guide'
      fullPath: '/resources/bcdr-guide'
      preLoaderRoute: typeof ResourcesBcdrGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/ai-agents-enterprise-guide': {
      id: '/resources/ai-agents-enterprise-guide'
      path: '/resources/ai-agents-enterprise-guide'
      fullPath: '/resources/ai-agents-enterprise-guide'
      preLoaderRoute: typeof ResourcesAiAgentsEnterpriseGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/manufacturing': {
      id: '/industries/manufacturing'
      path: '/industries/manufacturing'
      fullPath: '/industries/manufacturing'
      preLoaderRoute: typeof IndustriesManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/healthcare': {
      id: '/industries/healthcare'
      path: '/industries/healthcare'
      fullPath: '/industries/healthcare'
      preLoaderRoute: typeof IndustriesHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/fintech': {
      id: '/industries/fintech'
      path: '/industries/fintech'
      fullPath: '/industries/fintech'
      preLoaderRoute: typeof IndustriesFintechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  CareersRoute: CareersRoute,
  CareersApplyRoute: CareersApplyRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  InsightsRoute: InsightsRoute,
  MarketingRoute: MarketingRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProcessRoute: ProcessRoute,
  ProductsRoute: ProductsRoute,
  ProjectEstimatorRoute: ProjectEstimatorRoute,
  RequestAuditRoute: RequestAuditRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  IndustriesFintechRoute: IndustriesFintechRoute,
  IndustriesHealthcareRoute: IndustriesHealthcareRoute,
  IndustriesManufacturingRoute: IndustriesManufacturingRoute,
  ResourcesAiAgentsEnterpriseGuideRoute: ResourcesAiAgentsEnterpriseGuideRoute,
  ResourcesBcdrGuideRoute: ResourcesBcdrGuideRoute,
  ResourcesBlockchainSupplyChainRoute: ResourcesBlockchainSupplyChainRoute,
  ResourcesCloudMigrationCostGuideRoute: ResourcesCloudMigrationCostGuideRoute,
  ResourcesCyberEssentialsGuideRoute: ResourcesCyberEssentialsGuideRoute,
  ResourcesErpVsSapRoute: ResourcesErpVsSapRoute,
  ResourcesGenerativeAiEnterpriseRoute: ResourcesGenerativeAiEnterpriseRoute,
  ResourcesGlossaryRoute: ResourcesGlossaryRoute,
  ResourcesInHouseItVsManagedServicesRoute:
    ResourcesInHouseItVsManagedServicesRoute,
  ResourcesIso27001ChecklistRoute: ResourcesIso27001ChecklistRoute,
  ResourcesItStaffingVsInHouseRoute: ResourcesItStaffingVsInHouseRoute,
  ResourcesPenetrationTestingExplainedRoute:
    ResourcesPenetrationTestingExplainedRoute,
  ResourcesRansomwareRecoveryRoute: ResourcesRansomwareRecoveryRoute,
  ResourcesSocExplainedRoute: ResourcesSocExplainedRoute,
  ResourcesWhatIsVcioRoute: ResourcesWhatIsVcioRoute,
  ResourcesZeroTrustArchitectureRoute: ResourcesZeroTrustArchitectureRoute,
  ServicesBlockchainRoute: ServicesBlockchainRoute,
  ServicesCloudRoute: ServicesCloudRoute,
  ServicesConsultingRoute: ServicesConsultingRoute,
  ServicesCustomSoftwareRoute: ServicesCustomSoftwareRoute,
  ServicesCyberSecurityRoute: ServicesCyberSecurityRoute,
  ServicesErpRoute: ServicesErpRoute,
  ServicesItStaffingRoute: ServicesItStaffingRoute,
  ServicesManagedItRoute: ServicesManagedItRoute,
  ServicesMarketingRoute: ServicesMarketingRoute,
  ServicesMobileRoute: ServicesMobileRoute,
  ServicesNetworkRoute: ServicesNetworkRoute,
  ServicesWebDevelopmentRoute: ServicesWebDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
